### ISSUE TITLE
onLogin exception with Meteor 1.3

### ISSUE THREAD

**Issue by jykae** [apinf/meteor-accounts-admin-ui-bootstrap-3#1]
## Behaviour

After adding the package I get exception with Meteor 1.3:

```
I20160420-12:56:43.952(3)? Defining "admin" role.
I20160420-12:56:43.962(3)? Exception in onLogin callback: Error: After filtering out keys not in the schema, your modifier is now empty
I20160420-12:56:43.962(3)?     at [object Object].doValidate (packages/aldeed_collection2-core.js:403:11)
I20160420-12:56:43.962(3)?     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core.js:202:25)
I20160420-12:56:43.963(3)?     at Object._.extend._updateUserRoles (packages/alanning_roles.js:755:22)
I20160420-12:56:43.963(3)?     at Object._.extend.addUsersToRoles (packages/alanning_roles.js:221:11)
I20160420-12:56:43.963(3)?     at [object Object].Meteor.methods.addFirstUserToAdminRole (packages/brylie_first-user-admin.js:66:15)
I20160420-12:56:43.963(3)?     at maybeAuditArgumentChecks (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:2106:12)
I20160420-12:56:43.963(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:2025:20
I20160420-12:56:43.963(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
I20160420-12:56:43.963(3)?     at Server.apply (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:2024:47)
I20160420-12:56:43.963(3)?     at Server.call (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1958:19)
I20160420-12:56:43.964(3)?     at Package (packages/brylie_first-user-admin.js:94:10)
I20160420-12:56:43.964(3)?     at runAndHandleExceptions (packages/callback-hook.js:152:24)
I20160420-12:56:43.964(3)?     at packages/callback-hook.js:159:12
I20160420-12:56:43.964(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/accounts-base.js:669:5
I20160420-12:56:43.964(3)?     at [object Object]._.extend.each (packages/callback-hook.js:128:15)
I20160420-12:56:43.964(3)?     at AccountsServer.Ap._successfulLogin (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/accounts-base.js:668:21)
I20160420-12:56:43.964(3)?     at AccountsServer.Ap._attemptLogin (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/accounts-base.js:824:10)
I20160420-12:56:43.964(3)?     at [object Object].methods.login (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/accounts-base.js:974:21)
I20160420-12:56:43.965(3)?     at maybeAuditArgumentChecks (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:2106:12)
I20160420-12:56:43.966(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1047:22
I20160420-12:56:43.967(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
I20160420-12:56:43.967(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1046:43
I20160420-12:56:43.967(3)?     at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
I20160420-12:56:43.967(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1045:48
I20160420-12:56:43.967(3)?     at tryCallTwo (/Users/jykae/.meteor/packages/promise/.0.6.5.18r729a++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160420-12:56:43.967(3)?     at doResolve (/Users/jykae/.meteor/packages/promise/.0.6.5.18r729a++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
I20160420-12:56:43.968(3)?     at new Promise (/Users/jykae/.meteor/packages/promise/.0.6.5.18r729a++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:66:3)
I20160420-12:56:43.968(3)?     at Session.method (/Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:1023:23)
I20160420-12:56:43.968(3)?     at /Users/jykae/work/dipor-dashboard/.meteor/local/build/programs/server/packages/ddp-server.js:885:89
```

Also package dependencies would need some check.

```
Changes to your project's package version selections:

alanning:roles                   added, version 1.2.15
brylie:accounts-admin-ui         added, version 0.3.0
brylie:create-role-if-undefined  added, version 0.1.0
brylie:first-user-admin          added, version 0.1.9
meteor-platform                  added, version 1.2.4
standard-app-packages            added, version 1.0.7
```

Meteor platform 1.2 should not be fetched, what are "standard-app-packages"?

**Comment by 55** [comment]
add this to user schema:

```
  roles: {
    type: [String],
    blackbox: true,
    optional: true
  }
```

**Comment by jykae** [comment]
Awesome @elnzv that worked! You are genius 👍
